# -----------------------
#
# Build this project using python-build
# and then install it, and that's it.
#
# This is a sanity check that the build
# infrastructure is well formatted.
#
# -----------------------

name: Build

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest
    steps:
    - name: Get source code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install build requirements
      run: python -m pip install build

    - name: Create distributions
      run: python -m build . --sdist --wheel --outdir .

    - uses: actions/upload-artifact@v2
      with:
        name: tarball
        path: "*.tar.*"

    - uses: actions/upload-artifact@v2
      with:
        name: wheel
        path: "*.whl"

  test:
    name: Test distribution | Python ${{ matrix.python-version }} (${{ matrix.os }})
    needs:
     - build
    strategy:
      fail-fast: false
      matrix:
        os:
          - Ubuntu
        python-version:
          - 3.7
          - 3.8
          - 3.9
    runs-on: ${{ matrix.os }}-latest
    steps:
    - name: Download tarball
      uses: actions/download-artifact@v2
      with:
        name: tarball

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install this project
      run: python -m pip install *.tar.*

    - name: Package list
      run: python -m pip list installed

    - name: Test
      run: python -c "import pwca"
